name: Java Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'  # Используем Temurin JDK 22

      - name: Compile Java code
        run: javac -d out src/**/*.java

      - name: Run tests
        run: java -cp out org.junit.runner.JUnitCore AngleTest
