name: Java Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'  # Используем Temurin JDK 22

      - name: Download Lombok and JUnit dependencies
        run: |
          curl -L -o lombok.jar https://projectlombok.org/downloads/lombok.jar
          curl -L -o junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.0/junit-platform-console-standalone-1.8.0.jar

      - name: Compile Java code with Lombok and JUnit
        run: javac -cp ".:lombok.jar:junit-platform-console-standalone.jar" -d out $(find . -name "*.java")

      - name: Run JUnit tests
        run: java -cp "out:./junit-platform-console-standalone.jar" org.junit.platform.console.ConsoleLauncher --scan-classpath